version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - todo-app-network

volumes:
  data:
    driver: local

networks:
  todo-app-network:
    driver: bridge
